name = "quatf"
version = "0.1.0"
license = "Apache-2.0"
author = ["Tobias Ehlert"]
maintainer = ["@rivwgk"]
copyright = "2022-2023, Tobias Ehlert"

[build]
auto-tests = false
auto-examples = false

[install]
library = true
